project:
  type: website
  output-dir: docs

website:
  title: "Liver Disease Research Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: question1.qmd
        text: Research Question 1
      - href: question2.qmd
        text: Research Question 2
      - href: question3.qmd
        text: Research Question 3
      - href: question1code.qmd
        text: Code 
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

